[package]
name = "kore-example"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
kore-contract-sdk = "0.6.0"

[profile.release]
strip = "debuginfo"
lto = true

[lib]
crate-type = ["cdylib"]