networks:
  kore-example-network:
    external: true
      
services:
  mongodb:
    image: mongo
    container_name: mongodb-example
    ports:
      - "27017:27017"
    volumes:
      - ./mongoo:/data/db
    environment:
      # Usuario y contrase침a para el acceso a la base de datos
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: kore
    networks:
      kore-example-network:
        ipv4_address: 172.28.1.101

  sink:
      image: koreledgerhub/kore-sink:0.1.0
      container_name: kore-sink
      ports:
        - "5050:5050"
      environment:
        # Nivel de logs para la aplicaci칩n Rust (info, debug, trace, error, etc.)
        - RUST_LOG=info
        # Cadena de conexi칩n con el mongodb
        - KORE_MONGODB_URL=mongodb://user:kore@mongodb:27017
        # Direcci칩n HTTP en la que escucha el servicio
        - KORE_MONGODB_HTTP_ADDRESS=0.0.0.0:5050
      networks:
        kore-example-network:
          ipv4_address: 172.28.1.102

  kore-node:
    image: koreledgerhub/kore-http:0.7.3-rockdb-prometheus-debug
    container_name: kore-example2
    ports:
      - "3001:3000"
      - "50001:50000"
      - "3051:3050"
    environment:
      RUST_LOG: info
      KORE_HTTPS_DOC: true
      KORE_PASSWORD: koreledger
      KORE_NETWORK_NODE_TYPE: Addressable
      KORE_NETWORK_LISTEN_ADDRESSES: /ip4/0.0.0.0/tcp/50000
      KORE_NETWORK_ROUTING_ALLOW_LOCAL_ADDRESS_IN_DHT: true
      KORE_NETWORK_BOOT_NODES: /dns4/kore-example1/tcp/50000/p2p/{{peer-id}}
      KORE_BASE_SINK: kore-example:http://172.28.1.102:5050/sink/{{subject-id}}
    volumes:
      - ./kore_example2_db:/db
      - ./kore_example2_keys:/keys
    networks:
      - kore-example-network